### ISSUE TITLE
Editor.suggest() ignores nsamples parameter

### ISSUE THREAD

**Issue by luckytoilet** [marcotcr/checklist#10]
## Code to reproduce

```
import checklist
from checklist.editor import Editor

editor = Editor()
ret = editor.suggest('I am a {mask} {mask}.', nsamples=5)
print(ret)
```

## Expected behavior

It should generate 5 samples.

## Actual behavior

It generates 11000 samples.

Note that `editor.template()` correctly handles `nsamples`, only `editor.suggest()` is broken.

**Comment by marcotcr** [comment]
Thanks! Fixed in ca37ca6
