### ISSUE TITLE
Text Generation model for negation

### ISSUE THREAD

**Issue by emc5ud** [marcotcr/checklist#110]
Hello, I was considering working on a model that generates negated versions of simple (for now) input sentences. I was wondering if you thought that this could be a good feature for the Perturb class, or if you would prefer to keep the negation perturbations rules-based for now. Maybe there could be options to use one or the other? 

If you have ideas for some other more low hanging fruit I could help with, please let me know! I'm interested in contributing.

**Comment by marcotcr** [comment]
If you have a model that is not too big and is high-precision, I would be happy to replace the rules with it. You can take a look at [this other repo](https://github.com/tongshuangwu/polyjuice) for a counterfactual perturbation model, but it would be some work to make sure it's high precision. I don't think this is low hanging fruit, but I could be wrong :)
