### ISSUE TITLE
4. The CheckList process.ipynb : pipe([example]) incompatible type

### ISSUE THREAD

**Issue by surajbhat-01** [marcotcr/checklist#111]
When trying to run tutorial 4, I found that I get the following error:

TypeError: batch_text_or_text_pairs has to be a list (got <class 'tuple'>)

This is after copy-and-pasting the code from the tutorial and installing all the required packages. I have looked through the huggingface sourcecode and it seems as though the Text Classification pipeline only allows for a string or a list of strings. This error means that it is impossible to run the test suite as described in the tutorial.

**Comment by emc5ud** [comment]
Try wrapping the input in a list. e.g.

```
example = ('Which company should I join as a freshman, Google or Facebook?', 'Should I join Google as a freshman?')
pipe([[example]])
```

Note that I have two pairs of brackets.

**Comment by surajbhat-01** [comment]
Hi @emc5ud that fix worked, thank you!

That being said, when applying the same process to the following cell, there is still an issue. The following cell defines the pred_and_conf function, with the following code:

def pred_and_conf(data):
    raw_preds = pipe(data)
    print(raw_preds)
    sys.exit()
    preds = np.array([ int(p["label"][-1]) for p in raw_preds])
    pp = np.array([[p["score"], 1-p["score"]] if int(p["label"][-1]) == 0 else [1-p["score"], p["score"]] for p in raw_preds])
    return preds, pp

When converting pipe(data) to pipe([data]), I get the following error:

ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.

Any help would be greatly appreciated. Thank you!

**Comment by emc5ud** [comment]
Probably the same bug. I'm not sure the optimal way to fix this, but 

```
def pred_and_conf(data):
    data = [[d] for d in data]
    raw_preds = pipe(data)
    preds = np.array([ int(p["label"][-1]) for p in raw_preds])
    pp = np.array([[p["score"], 1-p["score"]] if int(p["label"][-1]) == 0 else [1-p["score"], p["score"]] for p in raw_preds])
    return preds, pp
```

Should work

**Comment by surajbhat-01** [comment]
Thank you, that fix did help get the tutorial to run!
