### ISSUE TITLE
Potential Case-Sensitivity Issue When Testing SQuAD

### ISSUE THREAD

**Issue by 12wollmana** [marcotcr/checklist#113]
I'm currently using CheckLists to test a SQuAD model.  I ran my model over the squad.json file and created a file that contains the predicted tokens.  My tokenizer lowercases all output.  When running suite.run_from_file and suite.summary, I'm getting a 100% fails rate on most sections (Vocabulary, Intensifiers, Profession vs nationality, Animal vs Vehicle v2, Synonyms, COMP, Antonyms, Fairness, Temporal, Understanding before/after, negation (both types), coref (both types), former/latter, and SRL tests).  Looking at the answer versus predicted, it looks like the only difference for many cases is that my output is lower-cased. 

Note that when I change some of my outputs to be cased properly, the fails rate does **not** improve.  So I'm not 100% sure that casing is the real issue or if there's a deeper issue.  I'm using the Tutorial code given in the README for SQuAD.

I've uploaded both my predictions and summary output as TXT files.

[normal_model.txt](https://github.com/marcotcr/checklist/files/7682288/normal_model.txt)
[Normal_Model_Summary.txt](https://github.com/marcotcr/checklist/files/7682291/Normal_Model_Summary.txt)

**Comment by marcotcr** [comment]
The expectation function I wrote for those tests is case sensitive, _and_ each testcase has multiple examples (and you only 'pass' a testcase if you get all examples correct). Anyway, you can run the following code to make the expectation function case-insensitive for the MFTs:
```python
from checklist.expect import Expect
import re
def clean(string):
    return re.sub(r'^(a|the|an|in|at) ', '', string).rstrip('.').lower()
def expect_squad(x, pred, conf, label=None, meta=None):
    return clean(pred) == clean(label)
expect_squad = Expect.single(expect_squad)
for t in suite.tests:
    if type(suite.tests[t]) == checklist.test_types.MFT:
        suite.tests[t].expect = expect_squad
```
I did this, reran the suite with the file you sent above, and all of the failures printed in `suite.summary()` are indeed cases where the answer from your model is different than the expected answer.
