### ISSUE TITLE
Invoking pip in setup.py breaks custom flags

### ISSUE THREAD

**Issue by sarnthil** [marcotcr/checklist#119]
Any flags passed to `pip` while installing `checklist` are not handed to the subprocess that is used to install jupyter. This makes it so that this can't be installed when using a custom `--index-url` (e.g. when installing `checklist` while in a restricted environment without internet access).

(Why is `jupyter` not just a normal dependency?)

**Comment by eddie-scio** [comment]
+1 to this -- having a free-flying dependency not actually expressed in `install_requires` also prevents various other tools (e.g. `pip-tools`) from freezing dependencies correctly.

**Comment by marcotcr** [comment]
Sorry for the delay. I don't know why this is the case, Jupyter [is a dependency](https://github.com/marcotcr/checklist/blob/9baab717e44e216697f7ef0730ee269db9ef7d5b/setup.py#L69). Am I missing something, and is there an easy way to fix this?
Thanks,

**Comment by eddie-scio** [comment]
Basically, why is there a subprocess that calls `pip install jupyter` [here](https://github.com/marcotcr/checklist/blob/master/setup.py#L12)?

**Comment by yukw777** [comment]
I came from https://github.com/python-poetry/poetry/issues/5068. `jupyter` is already specified as a dependency. You shouldn't run a command to install it again as @eddie-scio pointed out.

**Comment by ecederstrand** [comment]
Installing and enabling a Jupyter extension is not something that should happen during package build. You could add `jupyter` to `build_requires` but then you're enabling the extension in a `jupyter` that will be uninstalled when the build completes, which is pointless.

Arguably, it should be up to the user to enable the extension manually, but at least `BuildPyCommand`, `BdistEggCommand` and `EggInfoCommand` should just go away.
