### ISSUE TITLE
Where is the processed_qqp.pkl in the qqp notebook 

### ISSUE THREAD

**Issue by yyinsomnia** [marcotcr/checklist#12]
Where is the spacy_map =  pickle.load(open('/home/marcotcr/tmp/processed_qqp.pkl', 'rb'))

**Comment by marcotcr** [comment]
I guess I cached the spacy-processed questions rather than computing them in the notebook. You can process the questions yourself if you replace that line with
```python
all_questions = list(all_questions)
parsed_questions = list(nlp.pipe(all_questions))
spacy_map = dict([(x, y) for x, y in zip(all_questions, parsed_questions)])
```
I updated the notebook to reflect this in 64a810a
