### ISSUE TITLE
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long

### ISSUE THREAD

**Issue by WenRichard** [marcotcr/checklist#15]
I have to say that it's really a good job！I met some problem when I run the demo （Multilingual suggestions by RoBERTa ），I try to set language as English and Chinese，however they all fail to run，The reason is that “RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding)” ，I have no idea how to solve it ，it disturb me a lot time，can you give me some suggestions? I will appreciate it，by a way，my Environment are as follows：
1. torch==1.2.0 
2. torchvision==0.4.0
3. tensorflow-gpu==1.13.2
4.Python==3.6.1

**Comment by marcotcr** [comment]
I don't know what this is, but perhaps try updating your torch version?

**Comment by WenRichard** [comment]
> I don't know what this is, but perhaps try updating your torch version?

Thanks，Can you give me your detailed environment set？eg. torch version, python version, etc

**Comment by marcotcr** [comment]
python 3.6.8
torch 1.5.1

**Comment by DavidHuebner** [comment]
Hi, I just started with checklist and faced the same issue. Here is the error log:

[error_log.txt](https://github.com/marcotcr/checklist/files/5978170/error_log.txt)

My versions:
`python 3.8.5`
`torch==1.7.1`
