### ISSUE TITLE
Perturb.strip_punctuation possible endless loop for some cases

### ISSUE THREAD

**Issue by Riroaki** [marcotcr/checklist#19]
The `while` loop in `Perturb.strip_punctuation` function becomes an endless loop for inputs like `:`.
https://github.com/marcotcr/checklist/blob/e640d79f8c01e9e208256e355270ffdc6b21e162/checklist/perturb.py#L118

To reproduce it:
```python3
import spacy
from checklist.perturb import Perturb
model_path = ''  # Spacy model path
nlp = spacy.load(model_path)
sent = nlp(':')
Perturb.strip_punctuations(sent)  # Endless loop!
```

I checked the code and found `doc[-1].pos_` after stripping the last token `:` was always `PUNCT`... it seems like a spacy bug.

To avoid this, I suggest checking the length of `doc` in the while condition and return when the length of `doc` becomes 0.
```python3
while len(doc) and doc[-1].pos_ == 'PUNCT':
```

**Comment by marcotcr** [comment]
Fixed in dc31134.
Thanks for being so helpful!
