### ISSUE TITLE
Squad model source

### ISSUE THREAD

**Issue by berryweinst** [marcotcr/checklist#20]
Hi,

What is the source of the squad model with this API? (taken from the SQuaD tutorial)

```
model = bert_squad_model.BertSquad()
invert = lambda a: model.predict_pairs([(x[1], x[0]) for x in a])
new_pp = PredictorWrapper.wrap_predict(invert)
```

**Comment by marcotcr** [comment]
That is a wrapper I wrote to get predictions from huggingface's pretrained SQuAD model (bert-large). 
That wrapper is not necessary anymore, since they released pipelines ([this](https://huggingface.co/transformers/task_summary.html#extractive-question-answering) one in particular)
