### ISSUE TITLE
Tutorial not reproducable because some modules aren't part of the repo.

### ISSUE THREAD

**Issue by ashutosh-dwivedi-e3502** [marcotcr/checklist#23]
Following lines from tutorial-4 use the hard coded path to import a module which is not part of the repo.

```
sys.path.append('/home/marcotcr/work/ml-tests/')
from mltests import model_wrapper
model = model_wrapper.ModelWrapper()
```

**Comment by tongshuangwu** [comment]
Hi! 
As mentioned in the original `4. The CheckList process.ipynb` file, this is to be expected: we were running a QQP model locally, so 
> You won't be able to run them, but you can substitute your own model here if you want.

That said, we realize it can be frustrating and have revised tutorial-4 so it directly loads existing models/datasets hosted online. As of now, you should be able to run the entire tutorial without any change of code.

Please let us know if you still run into issues :)

**Comment by ashutosh-dwivedi-e3502** [comment]
Thanks a lot for posting the updated tutorial.
