### ISSUE TITLE
How to use checklist to evaluate a machine translation system?

### ISSUE THREAD

**Issue by catqaq** [marcotcr/checklist#29]

**Comment by tongshuangwu** [comment]
Hi there!
This is a rather broad question, and I don't really have a concrete answer. 

I imagine the keys are:
- To design the `Expectation` properly such that it allows reasonable tolerance on the eval score you are using;
- To correctly set your "labels." (in this case, your target sentences) For simple min. func tests, I think it wouldn't be too different from all the classification tasks, i.e. you just set your examples and labels. For perturbation tests, you might consider doing perturbations on both the source and the target sentence to get desired matches.

If you have drafts of CheckList tests for MT, please feel free to share them with us, and we'd be happy to discuss/help more!

**Comment by marcotcr** [comment]
I would just follow the process outline in [this tutorial](https://github.com/marcotcr/checklist/blob/master/notebooks/tutorials/4.%20The%20CheckList%20process.ipynb). You end up having to be more creative with expectation functions for a task like this, so you would end up creating expectations like 'words X, Y and Z are in the translation', 'word X is NOT in the translation', 'the translation contains AT LEAST one of the following words: [A, B, C]', etc.
