### ISSUE TITLE
Loading a finetuned model

### ISSUE THREAD

**Issue by farigys** [marcotcr/checklist#3]
Hi,

What's the easiest way to load a finetuned BERT model in the CheckList process? Seems like models are wrapped in a ModelWrapper class, and that wrapper is not available.

Thanks.

**Comment by marcotcr** [comment]
Hi,
That was just a wrapper we wrote for transformer models before they had `pipelines` and the like. 
[Here](https://github.com/marcotcr/checklist/blob/master/notebooks/tutorials/6.%20Testing%20transformer%20pipelines.ipynb) is a notebook where we test some pretrained pipelines with the same tests we have in the paper. You can replace the pretrained models with your own : )

Please reopen if this doesn't answer your question.
