### ISSUE TITLE
Extra `__init__.py` 

### ISSUE THREAD

**Issue by jinyongyoo** [marcotcr/checklist#32]
Hi,

In the root directory of this repo, there exists `__init__.py` file. I'm wondering if this is intentional or not, because it causes Python to think that the repo itself is a Python package when it's not. So for example, if we have a directory such as the following,
```
.
├── checklist (repo)
└── foo.py
```

and if I'm importing `checklist.editor` in `foo.py`, Python looks for `editor` in the repo, which it cannot find and trigger `ModuleNotFoundError`

**Comment by marcotcr** [comment]
It was not intentional. I don't know how that happened :)
Removed in 81fa7a2, thanks
