### ISSUE TITLE
Very useful product, I want to get some advices.

### ISSUE THREAD

**Issue by ahzz1207** [marcotcr/checklist#33]
Thanks for release this useful product, I recently modified it adapted to Chinese. If I want to use it to check/test some other models which not use softmax for last layer like NER model or not one example one probs. What change should I do to adapte to these models?

**Comment by marcotcr** [comment]
Most things in the library do not depend on the output being a list of probabilities. If you look at the SQuAD section in [this tutorial](https://github.com/marcotcr/checklist/blob/master/notebooks/tutorials/5.%20Testing%20transformer%20pipelines.ipynb), for example, you'll see that the model just outputs text predictions, and we run a bunch of tests on that. We created the tests in [this notebook](https://github.com/marcotcr/checklist/blob/master/notebooks/SQuAD.ipynb), so you can take a look at various expectation functions in there.

**Comment by ahzz1207** [comment]
Thanks for reply, I have already seen the SQuAD section. But outputs of other models like NER/POS is [batch, length] which get one more dimension compare to normal models. In this situation , I should to look at the Expect class to write a EXPECTATION FUNCTION for NER, is it right?
