### ISSUE TITLE
Dose the Perturb Module support Multilingual ?

### ISSUE THREAD

**Issue by hinesboy** [marcotcr/checklist#39]
Thank you for sharing such a great tool, it‘s really useful and amazing!

When i used the `Perturb.change_names` to get a INV test case, it could not perturb the names in my chinese dataset.
Does this module currently support multiple languages? can you tell me  how to use it?

**Comment by marcotcr** [comment]
Unfortunately it does not. That relies on being able to guess if it's a male or female name (so that the replacement is consistent), which I don't know how to do in other languages. You would have to implement your own : )
