### ISSUE TITLE
Using downstream-trained model for Editor

### ISSUE THREAD

**Issue by farigys** [marcotcr/checklist#44]
Can I use a transformer model that is fine-tuned on a downstream task as the masked language model for the Editor class?

**Comment by marcotcr** [comment]
Yes. If you set `model_name` when initializing the editor, we will internally call 
```
            self.tokenizer = AutoTokenizer.from_pretrained(model_name)
            self.model = AutoModelForMaskedLM.from_pretrained(model_name)
```
The default is `roberta-base`, but you can also give it a path instead of a name.
