### ISSUE TITLE
Multilingual perturbations?

### ISSUE THREAD

**Issue by kevinrobinson** [marcotcr/checklist#45]
Thanks for your work!  `perturb.by` is for English only, any plans for the API to support other languages?

**Comment by marcotcr** [comment]
The `perturb` function is general, but it's the only one. I don't plan on adding functions for other languages, unless you have a suggestion for functions that are general and would work for any language. I guess I could try writing `change_names` and `change_location` in such a way that it works with other languages without NER, but it would not be as good. Is that what you had in mind?

**Comment by kevinrobinson** [comment]
@marcotcr thanks!  I was looking at the methods using spacy annotations and figuring they'd work in multilingual settings, while methods like `add_negation` and `expand_contractions` are only for English, but implementations could be written in similar ways to build out support for other languages.

I'm mostly asking about what the scope of the project is and if you're continuing to develop it in any of those directions, so it's helpful to know that this isn't something you'll work on.  Thanks for sharing this awesome work 👍

**Comment by marcotcr** [comment]
I am trying to develop it in other directions that I think are more urgent : )

**Comment by kevinrobinson** [comment]
@marcotcr Yeah that's cool, I don't mean any judgment by asking :)  I'd be excited to read more about what directions you are working on when you're ready to share! 👍

**Comment by marcotcr** [comment]
I know, I didn't take your questions negatively at all :)
