### ISSUE TITLE
Can't get the template editor to show in colab

### ISSUE THREAD

**Issue by lapolonio** [marcotcr/checklist#5]
Code here:
https://colab.research.google.com/github/lapolonio/checklist/blob/master/notebooks/Sentiment.ipynb

**Comment by marcotcr** [comment]
It [sounds](https://github.com/googlecolab/colabtools/issues/60) like colab doesn't support custom ipywidgets, which we use for the template editor. Sorry!
You can still use `editor.suggest` or `editor.suggest_replace` (see [this](https://github.com/marcotcr/checklist/blob/master/notebooks/tutorials/1.%20Generating%20data.ipynb)) though.

**Comment by luckytoilet** [comment]
It also doesn't work on JupyterLab for me (running the first tutorial).

**Comment by marcotcr** [comment]
Er, sorry, JupyterLab also doesn't work with these extensions. I'll add a note to the readme.
