### ISSUE TITLE
Sentiment Analysis Different Results

### ISSUE THREAD

**Issue by burakisikli** [marcotcr/checklist#50]
Hi,
I tried to replicate the transformers results for sentiment analysis. In order to do that, I've created results based on tutorial in this link: https://github.com/marcotcr/checklist/blob/master/notebooks/tutorials/5.%20Testing%20transformer%20pipelines.ipynb. I compare it with release_data/sentiment/predictions/bert file. I expected same results but got different ones. Why is it happening?

5. Testing transformer pipelines Results:
![image](https://user-images.githubusercontent.com/982014/98992277-124a6e80-253e-11eb-938a-b72b0766c2c6.png)

File Results:
![image](https://user-images.githubusercontent.com/982014/98992338-20988a80-253e-11eb-9d13-86b652249574.png)

**Comment by marcotcr** [comment]
transformer pipelines didn't exist when we first ran this, the results in `release_data/sentiment/predictions/bert_file` are from a `bert-base` model we finetuned following the huggingface recipe at the time. The sentiment analysis pipeline uses `distillbert`
