### ISSUE TITLE
Missing documentation for Editor and Perturb classes (readthedocs)

### ISSUE THREAD

**Issue by prrao87** [marcotcr/checklist#51]
The [`editor`](https://checklist-nlp.readthedocs.io/en/latest/checklist.html#checklist-editor-module) and [`perturb`](https://checklist-nlp.readthedocs.io/en/latest/checklist.html#checklist-perturb-module) modules are currently missing documentation - is this still a work in progress? It would be very nice to be able to browse through the various methods and types for these modules, just like the `expect` module allows us to do currently, so I just wanted to point this out.

Thanks for this awesome library!

**Comment by marcotcr** [comment]
No, we had the documentation there, but there was a bug in our config script that generates the readthedocs. Thanks for pointing it out, should be fixed now.
