### ISSUE TITLE
SQuAD test doesn't work on Windows

### ISSUE THREAD

**Issue by ramarasty** [marcotcr/checklist#52]
The following line from the tutorial causes an error:
`suite.run_from_file(pred_path, overwrite=True, file_format='pred_only')`

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 6884: character maps to <undefined>`

I fixed the issue by changing [abstract_test.py line 15](https://github.com/marcotcr/checklist/blob/8cbc0f0d52b7297de7cdcbabe0a5f7ed3b77e1e5/checklist/abstract_test.py#L15) to:
`f = open(path, 'r', encoding='utf-8')`

**Comment by marcotcr** [comment]
thanks, fixed in 33c8ce9
