### ISSUE TITLE
Feature request Static HTML output

### ISSUE THREAD

**Issue by timothyjlaurent** [marcotcr/checklist#53]
Is it possible to output checklist results in some structured format, eg html, xml. 

We'd like to to integrate Checklist as a CI step and want to be able to persist the model performance.

**Comment by marcotcr** [comment]
If you run `test.get_stats()`, you get a dictionary with various statistics and test results. If you have a suite, you can run
```python
for test in suite.tests:
    stats = test.get_stats()
    # do something with the stats here, generate html or xml
```
Does this solve your problem or did I misunderstand what you're looking for?

**Comment by timothyjlaurent** [comment]
Yes, it does. Thanks for the pointer.

**Comment by prrao87** [comment]
Just in case anybody else stumbles across, what worked for me is the following (`suite.tests` returns an OrderedDict) :

```python
for test_name, test in suite.tests.items():
    stats = test.get_stats()
    # do something with the stats here, generate html or xml
```
