### ISSUE TITLE
BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by WSTC2007** [marcotcr/checklist#54]
Hello, when run 
`from checklist.perturb import Perturb`,
i meet an error: BadZipFile: File is not a zip file

**Comment by marcotcr** [comment]
Er, I have no idea why this would be, or what this error refers to. What version of python/checklist?

**Comment by WSTC2007** [comment]
The version of python is 3.7.3, and the version of checklist is 0.0.10.

**Comment by WSTC2007** [comment]
> Er, I have no idea why this would be, or what this error refers to. What version of python/checklist?

The version of python is 3.7.3, and the version of checklist is 0.0.10.

**Comment by marcotcr** [comment]
What OS? How did you install checklist?
