### ISSUE TITLE
pipeline step in 4. The CheckList process tutorial fails if there is no GPU

### ISSUE THREAD

**Issue by ramji-c** [marcotcr/checklist#57]
The code snippet `pipe = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, framework="pt", device=0)` in _cell#2_ of `checklist/notebooks/tutorials/4. The CheckList process.ipynb` fails on MacOS and other systems that do not have a GPU with the following error `assertionerror: torch not compiled with cuda enabled`. GPU devices are 0 indexed and changing the parameter `device=0` to `device=-1` resolves the problem. As there are no explicit requirements to have a GPU, it is perhaps better to change this parameter value so that notebook runs on all systems, including those that don't have a GPU.

**Comment by marcotcr** [comment]
Thanks. Setting it to -1 will run it on a CPU even if a GPU is available, but I added a comment in the tutorial.
