### ISSUE TITLE
how to replace with other masked language model 

### ISSUE THREAD

**Issue by bifeng** [marcotcr/checklist#60]

**Comment by marcotcr** [comment]
When you initialize `Editor`, use the argument `model_name` (default is `roberta-base`). The backend will initialize a tokenizer and a model using `AutoTokenizer.from_pretrained(model_name)` and `AutoModelForMaskedLM.from_pretrained(model_name)`, so either a name or a path should work.

**Comment by bifeng** [comment]
Thanks. It seems should use the model listed on 'https://huggingface.co/models.
