### ISSUE TITLE
What is spacy_map =  pickle.load(open('/home/marcotcr/tmp/processed_squad.pkl', 'rb'))

### ISSUE THREAD

**Issue by kingafy** [marcotcr/checklist#66]
What information is lying in the processed_squad.pkl file?I want to create a custom suite for Question answering on evaluation of a domain specific data.Can you elaborate what lies in processed_squad.pkl file and the real objective of using this in the code?

**Comment by marcotcr** [comment]
This is just a map of string to spacy doc, to avoid having to run spacy every time I run the notebook. You can ignore it and run spacy on your own data.
