### ISSUE TITLE
Information Needed on Checklist

### ISSUE THREAD

**Issue by kingafy** [marcotcr/checklist#67]
Is there any limitation on prediction wrapper to be used. The examples provided are using the Predictor Wrapper . Is it a mandate to use this or can we use our custom prediction pipeline. There are multiple pretrained models which do not return confidence score for a prediction. Also is there a way to convert the set of data created via suite and dump it directly to excel or csv and have our own prediction pipeline to evaluate the results.? Any advise on this would be highly appreciated.
Also do we have more sample notebooks on how to use it for Multi label classification/Summarization and Semantic similarity tasks?

**Comment by shaily99** [comment]
Have been using checklist for a while.

- To dump examples into a raw file checkout TestSuite.to_raw_file() [ref: checklist/test_suite.py]
- TestSuite also has a run_from_file(), which can read predictions from a file. It has multiple options, including having only predictions (and no confidence). It just takes confidence as 1 in that tuple by default [ref: test_suite.py, abstract_test.py]
- If you have to get external scores in a separate file and use it, here's another workaround: you can use the TestSuite.run_from_preds_confs() function. For this the press and confs can be supplied as arrays that you create externally, Just ensure that the order of the predictions is exactly same as that order of examples in the suite (that is in the same order as generated by to_raw_file() )

**Comment by marcotcr** [comment]
No, you can use whatever you want. See [this tutorial](https://github.com/marcotcr/checklist/blob/master/notebooks/tutorials/3.%20Test%20types,%20expectation%20functions,%20running%20tests.ipynb) in addition to what @shaily99 posted.
