### ISSUE TITLE
Possible to install this without mysql?

### ISSUE THREAD

**Issue by luckytoilet** [marcotcr/checklist#7]
When trying to install checklist, I run into the error: `OSError: mysql_config not found`. This happens during `pip install mysqlclient`, which is a dependency of the `pattern` package.

The simple solution of course is to install mysql. Unfortunately, this is not possible in many university shared computing environments due to security risks. As far as I can tell, mysql is not used anywhere in this tool. Is there any workaround to install it in an environment without mysql?

**Comment by marcotcr** [comment]
Yes, `pattern` is a pain to install without root. Let me see if there is a workaround. In the meantime, you can clone and remove the pattern dependency from `setup.py`.

**Comment by marcotcr** [comment]
Ok, I think the following works:
- clone the repo, remove the pattern dependency from `setup.py`
- from the repo folder, run: 
```bash
pip install pattern --no-deps 
pip install nltk
pip install -e .
```
The stuff that depends on pattern will still work.
