### ISSUE TITLE
The distribution of each test type?

### ISSUE THREAD

**Issue by eduOS** [marcotcr/checklist#71]
Can I use this technique to build a test set to check the performance of a model? If so, how many cases should each test type take in the test sample?

**Comment by marcotcr** [comment]
You can certainly build a test set, but I prefer to think of individual tests rather than creating a test _dataset_.
In terms of the process, let me point you to  [the paper](https://homes.cs.washington.edu/~marcotcr/acl20_checklist.pdf). How many cases in each cell is up to you : )
