### ISSUE TITLE
[feature] add_lexicon append option

### ISSUE THREAD

**Issue by jlema** [marcotcr/checklist#72]
Currently when adding a lexicon we can only overwrite (overwrite=True) entries, but cannot append to an existing lexicon. It would be great to add a feature for appending to an existing lexicon (append=True), with an option to remove duplicates (remove_duplicates=True).

Example usage:
```
editor.add_lexicon('adj', ['good', 'bad', 'great', 'terrible', 'excellent', 'poor', 'forgettable', 'memorable']) #first run
editor.add_lexicon('adj',` ['interesting','boring','bad'], append=True, remove_duplicates=True) #subsequent run
editor.lexicons['adj']
['good',
 'bad',
 'great',
 'terrible',
 'excellent',
 'poor',
 'forgettable',
 'memorable',
'interesting',
'boring']
```

**Comment by marcotcr** [comment]
Implemented in 94eb74d
