### ISSUE TITLE
[bug] editor.hypernyms returns a single suggestion, multiple expected

### ISSUE THREAD

**Issue by jlema** [marcotcr/checklist#74]
As per the [generating data notebook](https://github.com/marcotcr/checklist/blob/master/notebooks/tutorials/1.%20Generating%20data.ipynb) - **editor.hypernyms** is supposed to return multiple suggestions as follows:
```
editor.hypernyms('My dog eats other animals.', 'dog')
['animal', 'creature', 'food', 'beast', 'meat', 'mammal', 'person', 'organism']

```
Currently it is returning a single suggestion:
```
editor.hypernyms('My dog eats other animals.', 'dog')
['animal']

```
This also affects **related_words**:
Expected:
```
editor.related_words('My dog eats other animals.', 'dog')[:5]
['cat', 'animal', 'monkey', 'pet', 'elephant']

```
Current behavior:
```
editor.related_words('My dog eats other animals.', 'dog')[:5]
['pet']

```

**Comment by marcotcr** [comment]
The behavior you observe is due to the likelihood threshold (default is `5`). I guess RoBERTa doesn't like 'My food eats other animals', which is probably a good thing.
Examples:
```python
editor.hypernyms('My dog eats other animals.', 'dog', threshold=10)
```
> ['animal', 'food', 'meat', 'soul', 'beast', 'creature', 'person', 'organism', 'sausage', 'unit', 'being', 'male']

```python
editor.related_words('I have a pet dog.', 'dog')
```
> ['bird', 'kitten', 'puppy', 'toy']
