### ISSUE TITLE
Most test cases of reducing test_type discarded

### ISSUE THREAD

**Issue by iamanigeeit** [marcotcr/checklist#80]
For the SST suite,
Test type `Reducers`: 1966/2000 are discarded
Test type `"used to" should reduce`: 4202/4268 are discarded

The `expect` method returns `None` for these test cases. How can i fix this?

**Comment by marcotcr** [comment]
This test has the following description:
>A model should not be more confident on "I used to think X" when compared to "X", e.g. "I used to love this airline" should have less confidence than "I love this airline

Unfortunately, this can only fail if there is a margin for the model to be 'more confident' with 'I used to think X', i.e. if f(X) is not very close to 100% confidence. Thus, this test doesn't really work for really confident models, which is probably your case here. There is no way to fix it : )
