### ISSUE TITLE
Minor fix to Wordnet text generation score

### ISSUE THREAD

**Issue by CristianManta** [marcotcr/checklist#99]
Hi,

When you fixed a bug with Wordnet in commit bf51a392daea25a8f920cbf1c8474f76bcf41e0d, it removed the sensitivity to the threshold parameter from editor.synonyms. I found that it is caused by [this line](https://github.com/marcotcr/checklist/commit/bf51a392daea25a8f920cbf1c8474f76bcf41e0d#diff-af299d0834d6c051b16eb656ad0dee74a96551ba879fc553e97d7dfae84ba9b2R281). I think you rather meant

```python
score = score[0][-1]
```
Sorry for noticing it so late (I opened the original issue that prompted you to include the fix), I was also fooled by reading your diff, only to later notice that something was fishy with the quality of the synonyms suggested :)

Thanks
Cristian

**Comment by marcotcr** [comment]
Oh wow, yes, that was a blunder. Thanks for catching it!
Fixed in a7b39ac
